export const FETCHING_PARCELS_LOADING = 'FETCHING_PARCELS_LOADING';
export const FETCHING_PARCELS_SUCCESS = 'FETCHING_PARCELS_SUCCESS';
export const FETCHING_PARCELS_FAILURE = 'FETCHING_PARCELS_FAILURE';
export const CREATE_PARCEL_SUCCESS = 'CREATE_PARCEL_SUCCESS';
export const CREATE_PARCEL_FAILURE = 'CREATE_PARCEL_FAILURE';
export const PARCEL_IS_LOADING = 'PARCEL_IS_LOADING';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_CLIENT_ERROR = 'SET_CLIENT_ERROR';
export const CANCEL_PARCEL_SUCCESS = 'CANCEL_PARCEL_SUCCESS';
export const CANCEL_PARCEL_FAILURE = 'CANCEL_PARCEL_FAILURE';
export const CANCEL_PARCEL_LOADING = 'CANCEL_PARCEL_LOADING';

// APPLICATON CONSTANTS
export const API_BASE_URL = 'http://localhost:3030/api/v1';
export const ACCESS_TOKEN = null;
//AUTHENTICATION CONSTANTS
export const LOGIN_USER_LOADING = 'LOGIN_USER_LOADING';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';

export const SIGNUP_USER_LOADING = 'SIGNUP_USER_LOADING';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';

export const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED';
export const SET_IS_NOT_AUTHENTICATED = 'SET_IS_NOT_AUTHENTICATED';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
