export const FETCHING_PARCEL_SUCCESS = 'FETCHING_FEEDS_SUCCESS';
export const FETCHING_PARCEL_FAILURE = 'FETCHING_FEEDS_FAILURE';
export const POST_PARCEL_ORDER = 'POST_PARCEL_ORDER';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_CLIENT_ERROR = 'SET_CLIENT_ERROR';

// APPLICATON CONSTANTS
export const API_BASE_URL = 'http://localhost:3030/api/v1';
export const ACCESS_TOKEN = null;
//AUTHENTICATION CONSTANTS
export const LOGIN_USER_LOADING = 'LOGIN_USER_LOADING';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';

export const SIGNUP_USER_LOADING = 'SIGNUP_USER_LOADING';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';

export const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED';
export const SET_IS_NOT_AUTHENTICATED = 'SET_IS_NOT_AUTHENTICATED';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
